server:
  port: 10001
spring:
  application:
    name: service-producer
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  type-aliases-package: com.qf.cloud031_provider.pojo
  mapper-locations: classpath:mapping/*.xml
